### --- Start RHEL7 Specific --- ###
# If docker_from_centos is false, the task assumes repos with docker packages are enabled on the host
docker_from_centos: true
# If firewalld is on. This will add docker0 interface to the trusted zone
use_firewalld_enabled: true
# Ansible's firewalld module requires python-firewall, which may only be available in python2
firewalld_ansible_python_interpreter: /usr/bin/python2.7
# If selinux is enabled. When using mounted disk this sets the context for the mounted disk path
selinux_enforcing: true
### --- End RHEL7 Specific --- ###

# Enable or Disable Ansible Roles
install_dependencies_enabled: true
copy_files_enabled: true
install_tfe_enabled: true

# If you desire to use a particular python interperter version on the remote host.
ansible_python_interpreter: /usr/bin/python3.6

# SSH Settings
ansible_ssh_private_key_file: tfe.pem
ansible_user: user

# Airgap Settings
airgap_install: false
pkg_repos_reachable_with_airgap: true
install_docker_before: true

# Are the files, such as the license, airgap, etc, already on the remote host?
# If false, these will be sourced from roles/copy-files/files/ dir
files_on_system: false

# TFE Installation file locations
tfe_installer_dir: /opt/tfe/installer
tfe_config_dir: /etc
tfe_settings_path: /etc/tfe-settings.json
tfe_license_path: /etc
tfe_airgap_path: /opt/tfe/installer
repl_bundle_path: /opt/tfe/installer
repl_conf_path: /etc/replicated.conf

# TFE TLS Certificates file names. Certificates will go in the `tfe_config_dir` on the remote host
# Certificates should be places in the roles/copy-files/files dir on the ansible control node
tfe_cert_name: tfe-cert.pem  
tfe_privkey_name: tfe-cert-key.pem
ca_bundle_name: tfe-ca-bundle.pem

# Custom certificate authority (CA) bundle. 
# JSON does not allow raw newline characters, so replace any newlines in the data with \n.
# The command awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' tfe-ca-bundle.pem can assist.
ca_cert_data: null

# TFE File Names
license_name: tfe-license.rli

# Not required unless airgap_install: true
airgap_bund_name: tfe-681.airgap
replicated_tar_name: replicated-2.54.1.tar.gz

# TFE Install Secrets
console_password: mytfeconsolepass
encryption_password: mytfeencpass

# TFE install settings - Replicated config file
tfe_hostname: my.company.com
tfe_release_sequence: 681
tls_bootstrap_type: server-path
remove_import_settings_from: "false"

# Mounted disk or External Services
mounted_disk: true

# TFE App Settings - tfe-settings.json. True = 1 False = 0
aws_access_key_id: null
aws_secret_access_key: null
production_type: disk
disk_path: /opt/tfe-ent
capacity_concurrency: 10
capacity_memory: 512
enable_metrics_collection: 0
metrics_endpoint_enabled: 0
metrics_endpoint_port_http: null
metrics_endpoint_port_https: null
extra_no_proxy: null
force_tls: 0
hairpin_addressing: 0
pg_dbname: null
pg_netloc: null
pg_password: null
pg_user: null
restrict_worker_metadata_access: 1
custom_s3_endpoint: false
s3_app_endpoint_url: null
s3_app_bucket_name: null
s3_app_bucket_region: null
s3_use_kms: false
s3_sse_kms_key_id: null
tbw_image: null
http_proxy: false
http_proxy_name: null


# TFE App Settings - active/active - True = 1 False = 0
enable_active_active: 0
redis_host: null
redis_pass: null
redis_port: null
redis_use_password_auth: null
redis_use_tls: null


# TFE App settints - Log Forwarding - True = 1 False = 0
log_forwarding_enabled: 0
log_forwarding_config: null

# Upgrades - Airgap
upgrade_target_version: "681"