# Enable or Disable Ansible Roles
install_dependencies_enabled: false
copy_files_enabled: true
install_tfe_enabled: true
uninstall_tfe_enabled: false

# SSH Settings
ansible_ssh_private_key_file: tfeadmin-key-josh.pem
ansible_user: tfeadmin

# Airgap Settings
airgap_install: true
pkg_repos_reachable_with_airgap: true
install_docker_before: true

# Are the files, such as the license, airgap, etc, already on the remote host?
# If false, these will be sourced from roles/copy-files/files/ dir
files_on_system: false

# TFE Installation file locations
tfe_installer_dir: /opt/tfe/installer
tfe_config_dir: /etc
tfe_settings_path: /etc/tfe-settings.json
tfe_license_path: /etc/license.rli
tfe_airgap_path: /opt/tfe/installer/tfe-bundle.airgap
repl_bundle_path: /opt/tfe/installer/replicated.tar.gz
repl_conf_path: /etc/replicated.conf # can i interpolate the /etc part?

# TFE TLS Certificates file names. Certificates go in the `tfe_config_dir`
tfe_cert_name: tfe-cert.pem  
tfe_privkey_name: tfe-cert-key.pem
ca_bundle_name: tfe-ca-bundle.pem

# Custom certificate authority (CA) bundle. 
# JSON does not allow raw newline characters, so replace any newlines in the data with \n.
# The command awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' tfe-ca-bundle.pem can assist.
ca_cert_data: -----BEGIN CERTIFICATE-----\nMIIFIDCCBAigAwIBAgISA0t9452nQ7vgwYP4F+v/9FPCMA0GCSqGSIb3DQEBCwUA\nMDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD\nEwJSMzAeFw0yMjExMzAxMzM0NDlaFw0yMzAyMjgxMzM0NDhaMBkxFzAVBgNVBAMM\nDiouaXMudGZlLnJvY2tzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA\nxFIScVD5/lyZEw15hiuaXBnvR6oeoMBRxJI9ySVW6ZNh7Pvk2N4xA1ZKPVmLNyBT\ngw+bRJJePqbGopBzm4JA7isFA9CwdzT2xb9Mj1Uk2QhlCiNJDSUSuaN59FyxL8YQ\ni4MsLYGTIDZELudr/5yaT/D/AUAnVyLkFQts1NwHun1ebx4FlgpCMZnf5ojvgEk+\nJHtGqWvNxzEwIFSUkmhyNTIMAQWogI3qxMLj7EN97PUG+RTtZUw74EK3RZRuQzU6\nakM15+KkYxxG/LFw7nMZLFVTeEILZ+5rSKr35Bigpy+3l95V9eoMR79SQLcZOVO6\nsx5tnXHfNA2n95AHE0AFmwIDAQABo4ICRzCCAkMwDgYDVR0PAQH/BAQDAgWgMB0G\nA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1Ud\nDgQWBBReMhC6t/RdVMcInFBvHnlP37rcdzAfBgNVHSMEGDAWgBQULrMXt1hWy65Q\nCUDmH6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9y\nMy5vLmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3Jn\nLzAZBgNVHREEEjAQgg4qLmlzLnRmZS5yb2NrczBMBgNVHSAERTBDMAgGBmeBDAEC\nATA3BgsrBgEEAYLfEwEBATAoMCYGCCsGAQUFBwIBFhpodHRwOi8vY3BzLmxldHNl\nbmNyeXB0Lm9yZzCCAQIGCisGAQQB1nkCBAIEgfMEgfAA7gB1AHoyjFTYty22IOo4\n4FIe6YQWcDIThU070ivBOlejUutSAAABhMj2NdMAAAQDAEYwRAIgPb+TgXFbVOux\njWs/JONMBzgf5rCBH3fTsox0/K+4fJUCIFfESE/s4UNTELbu9vBbzhkvYaPQrRKu\nbrJmyy+ZOt1VAHUA6D7Q2j71BjUy51covIlryQPTy9ERa+zraeF3fW0GvW4AAAGE\nyPY3qwAABAMARjBEAiBCgY/i3SPVRwEah/s/FQMtqcGwcIg6bp30+JCrR85T2QIg\nSDLMlTHtVgmxexn9VqOF5ts5XNdVVVb14R6y25ryqZkwDQYJKoZIhvcNAQELBQAD\nggEBAHgMtLzRT3DdRj7JReneL87h60bFpE6UPRRxCAjmPWR84fwQ9tqUBG6hkMgV\nMO8Gx/SsBl0LGabn3kwsuZwzBEeg+DVuRFdQBeZLBNzmv1ubYp+V7JjRbr92vEgl\nd18HAGEEpm46flwfWnBPAOV6UZozDpDyqzLzqrYn39GuUXTOeDcyVILGFmDOTBm8\n4/xraEVfYKVFZFLgIXGEIRGChwiDOkTNKc8EYJDoNjR5SSPVJ7Y13zXVj35NtRcQ\nZp3D5OyVSbaFiFcVzID+KQphqWAR+XhPHDeix1lXcF9CUKeQfHTU6WF2guI5ZnqH\no+E/9G7ab7CDVMNovXb4J7PHw+Q=\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw\nTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\ncmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw\nWhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg\nRW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK\nAoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP\nR5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx\nsxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm\nNHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg\nZ3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG\n/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC\nAYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB\nAf8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA\nFHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw\nAoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw\nOi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB\ngt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W\nPTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl\nikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz\nCkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm\nlJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4\navAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2\nyJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O\nyK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids\nhCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+\nHlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv\nMldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX\nnLRbwHOoq7hHwg==\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\nMIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/\nMSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT\nDkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow\nTzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\ncmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB\nAQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC\nov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL\nwYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D\nLtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK\n4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5\nbHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y\nsR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ\nXmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4\nFQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc\nSLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql\nPRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND\nTwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw\nSwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1\nc3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx\n+tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB\nATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu\nb3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E\nU1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu\nMA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC\n5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW\n9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG\nWCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O\nhe8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC\nDfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5\n-----END CERTIFICATE-----\n

# TFE File Names
license_name: tfe-license.rli
airgap_bund_name: TFE-667.airgap
replicated_tar_name: replicated-2.54.0.tar.gz

# TFE Install Secrets
console_password: mytfeconsolepass
encryption_password: mytfeencpass

# TFE install settings - Replicated config file
tfe_hostname: bofa.is.tfe.rocks
tfe_release_sequence: 0
tls_bootstrap_type: server-path
remove_import_settings_from: "false"

# Should be eth0 or equivilent, not docker0
tfe_private_ip: 172.30.0.4

# Mounted disk or External Services
mounted_disk: true

# TFE App Settings - tfe-settings.json. True = 1 False = 0
production_type: disk
disk_path: /opt/terraform-enterprise
capacity_concurrency: 10
capacity_memory: 512
enable_active_active: 0
enable_metrics_collection: 0
metrics_endpoint_enabled: 0
metrics_endpoint_port_http: null
metrics_endpoint_port_https: null
extra_no_proxy: null
force_tls: 0
hairpin_addressing: 1
pg_dbname: test
pg_netloc: test
pg_password: tfeadminpass
pg_user: tfeadmin
restrict_worker_metadata_access: 1
s3_app_endpoint_url: test
s3_app_bucket_name: test
s3_app_bucket_region: us-east-1
tbw_image: null
http_proxy: null


# TFE App Settings - active/active - True = 1 False = 0
redis_host: null
redis_pass: null
redis_port: null
redis_use_password_auth: null
redis_use_tls: null


# TFE App settints - Log Forwarding - True = 1 False = 0
log_forwarding_enabled: 0
log_forwarding_config: null