---
# tasks file for install-dependencies

# Ubuntu
- name: Add Docker GPG apt Key
  when: ansible_facts['distribution'] == "Ubuntu"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  when: ansible_facts['distribution'] == "Ubuntu"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  when: ansible_facts['distribution'] == "Ubuntu"
  apt:
    name: docker-ce=5:20.10.7~3-0~ubuntu-focal
    update_cache: true

# RHEL7
- name: Install required packages [yum-utils, device-mapper-persistent-data, lvm2]
  when: (ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker repo from CentOS repos [edge]
  when: (docker_from_centos and ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  yum_repository:
    name: docker-ce-edge
    file: docker-ce
    description: docker centos edge repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/edge/
    enabled: yes

- name: Add Docker repo from CentOS repos [test]
  when: (docker_from_centos and ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  yum_repository:
    name: docker-ce-test
    file: docker-ce
    description: docker centos test repo
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/test/
    enabled: yes

- name: Install Docker
  when: (ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  yum:
    name:
      - docker-ce-20.10.7-3.el7
      - docker-ce-cli-20.10.7-3.el7
      - containerd.io
      - container-selinux
    state: present
    update_cache: true

- name: Start Docker service
  when: (ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  service:
    name: docker
    state: started
    enabled: yes
