---
# tasks file for uninstall-tfe

- name: Copy the uninstall script to host
  copy:
    src: files/uninstall.sh
    dest: "{{tfe_installer_dir}}/uninstall.sh"
    mode: '0755'

- name: Run the `uninstall.sh` script to uninstall TFE
  expect: 
    chdir: "{{tfe_installer_dir}}"
    command: "./uninstall.sh"
    responses:
       (?i)(y/n): "y"
       (?i)There appear to be Replicated snapshots: "2"
       (?i)I can now clean up the Docker images for you: "2"
  register: uninstall_out

- debug: msg="{{ uninstall_out }}"

- name: Remove mounted disk path
  when: mounted_disk
  file:
    path: "{{disk_path}}"
    state: absent