---
# tasks file for uninstall-tfe
- name: "[Ubuntu] Install pip"
  when: ansible_facts['distribution'] == "Ubuntu"
  apt:
    name:
      - python3-pip
    update_cache: yes
    state: present

- name: "[RHEL7] Install pip"
  when: (ansible_facts['distribution'] == "RedHat" and ansible_distribution_major_version == "7")
  yum:
    name:
      - python3-pip
    state: latest


- name: Install pexpect
  pip:
    name: pexpect

- name: Copy the uninstall script to host
  copy:
    src: files/uninstall.sh
    dest: "{{tfe_installer_dir}}/uninstall.sh"
    mode: '0755'

- name: Run the `uninstall.sh` script to uninstall TFE
  expect: 
    chdir: "{{tfe_installer_dir}}"
    command: "./uninstall.sh"
    responses:
       (?i)(y/n): "y"
       (?i)There appear to be Replicated snapshots: "2"
       (?i)I can now clean up the Docker images for you: "2"
  register: uninstall_out

- debug: msg="{{ uninstall_out }}"

- name: Remove mounted disk path
  when: mounted_disk
  file:
    path: "{{disk_path}}"
    state: absent